trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples
    - repository: library
      type: github
      name: osisoft/sample-ocs-sample_libraries-java
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: SDS_Java

jobs:
  - job: Tests_OCS
    strategy:
      maxParallel: 1 # Avoid conflicts in OCS
      matrix:
        linux:
          agentOS: Linux
        windows:
          agentOS: Windows_NT
    pool:
      name: 00-OSIManaged-Containers
      demands: Agent.OS -equals $(agentOS)
    steps:
      - checkout: self
        path: 's'
      - checkout: library
        path: 's/lib'

      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, NamespaceId, CommunityId, ClientId, ClientSecret'

      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
          jdkDestinationDirectory: '$(Agent.ToolsDirectory)/jdk11'
          cleanDestinationDirectory: false
        condition: eq(variables['Agent.OS'], 'Linux')

      - script: mvn install -f pom.xml
        workingDirectory: $(Build.SourcesDirectory)/lib
        displayName: 'Maven install library'

      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)/pom.xml'
          goals: 'test'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Run tests'

  - job: Tests_EDS
    pool:
      name: 00-OSIManaged-Containers
      demands: sku2 -equals VSBuildTools.v16.11.7plusAndEDS
    variables:
      - name: TenantId
        value: default
      - name: NamespaceId
        value: default
      - name: Resource
        value: http://localhost:5590
    steps:
      - checkout: self
        path: 's'
      - checkout: library
        path: 's/lib'

      - template: '/miscellaneous/build_templates/appsettings.yml@templates'

      - script: mvn install -f pom.xml
        workingDirectory: $(Build.SourcesDirectory)/lib
        displayName: 'Maven install library'

      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)/pom.xml'
          goals: 'test'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - checkout: self
          path: 's'
        - checkout: library
          path: 's/lib'

        - script: mvn install -f pom.xml
          workingDirectory: $(Build.SourcesDirectory)/lib
          displayName: 'Maven install library'

        - task: Maven@3
          inputs:
            mavenPomFile: '$(Build.SourcesDirectory)/pom.xml'
            goals: 'package'
            options: '-DskipTests'
          displayName: 'Build'
